version: "3.7"

services:
  init:
    build: ./backup_init
    environment:
      BACKUP_FOLDER: ${BACKUP_FOLDER}
    volumes:
      - "${BACKUP_PATH:-backup-path}:/mnt"

  odoo-db-backup:
    depends_on:
      init:
        condition: service_completed_successfully
    image: mekomsolutions/postgres_backup:9556d7c
    environment:
      DB_HOST: odoo-postgresql
      DB_NAME:  odoo
      DB_USERNAME: ${ODOO_DB_USER}
      DB_PASSWORD: ${ODOO_DB_PASSWORD}
      DB_PORT: 5432
    networks:
      bahmni:
        aliases:
          - odoo-db-backup
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}:/opt/backup/"

  openmrs-db-backup:
    depends_on:
    init:
      condition: service_completed_successfully
    image: mekomsolutions/mysql_backup:9556d7c
    environment:
      DB_HOST: openmrs-mysql
      DB_NAME:  openmrs
      DB_USERNAME: ${OPENMRS_DB_USER}
      DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
    networks:
      bahmni:
        aliases:
          - openmrs-db-backup
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}:/opt/backup/"

  openelis-db-backup:
    depends_on:
      init:
        condition: service_completed_successfully
    image: mekomsolutions/postgres_backup:9556d7c
    environment:
      DB_HOST: postgresql
      DB_NAME:  ${OPENELIS_DB_NAME}
      DB_USERNAME: ${OPENELIS_DB_USER}
      DB_PASSWORD: ${OPENELIS_DB_PASSWORD}
      DB_PORT: 5432
    networks:
      bahmni:
        aliases:
          - openelis-db-backup
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}:/opt/backup/"

  eip-client-backup:
    depends_on:
      init:
        condition: service_completed_successfully
    image: mekomsolutions/mysql_backup:9556d7c
    environment:
      DB_HOST: mysql
      DB_NAME:  ${EIP_DB_NAME}
      DB_USERNAME: ${EIP_DB_USER}
      DB_PASSWORD: ${EIP_DB_PASSWORD}
    networks:
      bahmni:
        aliases:
          - openmrs-db-backup
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}:/opt/backup/"

  bahmni-home-backup:
    image: mekomsolutions/filestore_backup:9556d7c
    environment:
      FILESTORE_PATH: /mnt/home
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}/bahmni_home:/opt/backup/"
      - ${BAHMNI_HOME_PATH:-bahmni-home}:/mnt/home

  odoo-filestore-backup:
    depends_on:
      init:
        condition: service_completed_successfully
    image: mekomsolutions/filestore_backup:9556d7c
    environment:
      FILESTORE_PATH: /mnt/odoo
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}/odoo_filestore:/opt/backup/"
      - ${ODOO_FILESTORE:-odoo-filestore}:/mnt/odoo
  odoo-checksum-backup:
    depends_on:
      init:
        condition: service_completed_successfully
    image: mekomsolutions/filestore_backup:9556d7c
    environment:
      FILESTORE_PATH: /mnt/odoo_config_checksum
    volumes:
      - "${BACKUP_PATH:-backup-path}/${BACKUP_FOLDER}/odoo_checksums:/opt/backup/"
      - "${ODOO_CONFIG_CHECKSUM_PATH:-odoo-checksums}:/mnt/odoo_config_checksum"
volumes:
  backup-path: ~
  odoo-filestore: ~
  bahmni-home: ~
  odoo-checksums: ~

networks:
  bahmni:
